config/routes.rb
GorucoRadiator::Application.routes.draw do
  devise_for  :admins,
              :controllers => { :sessions => "admins/sessions" }
  devise_for  :admins,
              :path => "admin", 
              :path_names => { :sign_in => "" }, 
              :controllers => { :sessions => "admins/sessions" }

  scope :path => :admins, :module => "admins" do
    resource :manages
  end
  resources :events, :only => "index"
  resources :twitter, :only => "" do
      get 'hashtag', :on => :collection
      get 'handle', :on => :collection
  end
  resources :instagram, :only => "index"
  resources :photo_stream, :only => :index
  resources :foursquare, :only => "index"

  root :to => "home#index"

end

app/controllers/admins/manages_controller.rb
require 'yaml'

class Admins::ManagesController < ApplicationController 
  layout "admin"

  before_filter :authenticate_admin!

  def show 
    config = YAML.load_file("config/config.yml")

    @conference = Conference.new
    @conference.twitter_handle = config["twitter_handle"]
    @conference.twitter_hashtag = config["twitter_hashtag"]
    @conference.instagram_client_id = config["instagram_client_id"]
    @conference.instagram_hashtag = config["instagram_hashtag"]
    @conference.foursquare_venue_id = config["foursquare_venue_id"]
    @conference.foursquare_venue_name = config["foursquare_venue_name"]
    @conference.foursquare_oauth_token = config["foursquare_oauth_token"]
    @conference.sponsors = config["sponsors"]
    @conference.events = config["events"]
  end

  def update
    config = YAML.load_file("#{Rails.root}/config/config.yml")

    @conference = params[:conference]
    @conference["sponsors"] = config["sponsors"]
    @conference["events"] = config["events"]
   
    @conference.each do |key, value|
      APP_CONFIG[key] = value
    end

    File.open("config/config.yml", "w") { |f| YAML.dump(@conference, f) }

    redirect_to :root
  end
end

app/views/admins/manages/show.html.erb
<div id="conference">
  <%= form_for @conference, :url => manages_path(@conference), :html => { :method => :put } do |f| %>
    <p>
    <label>Twitter Handle:</label>
    <%= f.text_field :twitter_handle %>
    </p>
    <p>
    <label>Twitter Hashtag:</label>
    <%= f.text_field :twitter_hashtag %>
    </p>
    <p>
    <label>Instagram Hashtag:</label>
    <%= f.text_field :instagram_hashtag %>
    </p>
    <p>
    <label>Instagram Client Id:</label>
    <%= f.text_field :instagram_client_id %>
    </p>
    <p>
    <label>Foursquare Venue Id</label>
    <%= f.text_field :foursquare_venue_id %>
    </p>
    <p>
    <label>Foursquare Venue Name</label>
    <%= f.text_field :foursquare_venue_name %>
    </p>
    <p>
    <label>Foursquare Oauth Token</label>
    <%= f.text_field :foursquare_oauth_token %>
    </p>

    <%= f.submit "Update Radiator!" %>
  <% end %>
</div>

<div id="signout">
  <%= link_to 'Sign Out', destroy_admin_session_path %>
</div>