config/routes.rb
GorucoRadiator::Application.routes.draw do
  devise_for  :admins,
              :controllers => { :sessions => "admins/sessions" }
  devise_for  :admins,
              :path => "admin", 
              :path_names => { :sign_in => "" }, 
              :controllers => { :sessions => "admins/sessions" }

  scope :path => :admins, :module => "admins" do
    resource :manages
  end
  resources :events, :only => "index"
  resources :twitter, :only => "" do
      get 'hashtag', :on => :collection
      get 'handle', :on => :collection
  end
  resources :instagram, :only => "index"
  resources :photo_stream, :only => :index
  resources :foursquare, :only => "index"

  root :to => "home#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GorucoRadiator</title>
    <%= stylesheet_link_tag "common", :media => :all %>
    <%= stylesheet_link_tag "admin", :media => :all %>
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <%= csrf_meta_tag %>
    <%= javascript_include_tag 'jquery', 'rails.validations' -%>
  </head>
  <body>
    <div id="wrapper">
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GorucoRadiator</title>
    <%= stylesheet_link_tag "common", :media => :all %>
    <%= stylesheet_link_tag "screen", :media => "screen and (min-device-width: 481px)" %>
    <%= stylesheet_link_tag "mobile", :media => "handheld, (max-device-width: 480px)" %>
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="wrap">
      <div id="wrap_content">
        <div id="header">
          <%= image_tag 'logo.png', :id => "logo" %>
          <%= render 'sponsor' %>
        </div>
        <div class="clear"></div>

        <%= yield %>
      </div>

      <% if admin_signed_in? %>
        <div id="signout">
          <%= link_to "Sign Out", destroy_admin_session_path %>
        </div>
      <% end %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>